### ISSUE TITLE
Recommendations for plugins

### ISSUE THREAD

**Issue by jiyuuchc** [trackmate-sc/TrackMate#282]
We wrote a TrackMate detector [plugin](https://github.com/jiyuuchc/TrackMate-Lacss/). This is a deep learning based cell detector, originally developed for a local hematology research project, but we are considering releasing it to the public. 

While Trackmate already includes several cell-detector options, some users might still find our alternative useful due to its [speed](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10243149).

So before we upload it to image.net, we would like to double check with the upstream to see if there is any recommended "best-practice" for doing this, e.g., just off the top of my head:

  - Package name: we currently use ij.plugin.trackmate.lacss, which in theory could lead to collision. Should we change that?
  - Artifact name. Any conventions?
  - Is it ok to hijack trackmate's mailing list tag, e.g. https://forum.image.sc/tag/trackmate, for the plugin's POM metadata?
  - Anything else?

**Comment by tinevez** [comment]
Hello @jiyuuchc 


> We wrote a TrackMate detector [plugin](https://github.com/jiyuuchc/TrackMate-Lacss/). This is a deep learning based cell detector, originally developed for a local hematology research project, but we are considering releasing it to the public.
> While Trackmate already includes several cell-detector options, some users might still find our alternative useful due to its [speed](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=10243149).

Awesome! We really built TrackMate so that it cab extended by others, and this issue makes my day!
I can't wait to study the technology you used to communicate with Python. 

> So before we upload it to image.net, we would like to double check with the upstream to see if there is any recommended "best-practice" for doing this, e.g., just off the top of my head:
> 
> * Package name: we currently use ij.plugin.trackmate.lacss, which in theory could lead to collision. Should we change that?

I would recommend using the same root that of the TrackMate packages, though:
`fiji.plugin.trackmate.detection.lacss`

so that it fits nicely under the same package hierarchy common to all detectors. 

> * Artifact name. Any conventions?

We recommend `TrackMate-Something`, with a capital 'S'. See for instance the artifact names for the other extensions:
https://github.com/orgs/trackmate-sc/repositories

> * Is it ok to hijack trackmate's mailing list tag, e.g. https://forum.image.sc/tag/trackmate, for the plugin's POM metadata?

Totally ok. 

> * Anything else?

We are working on a v8 version, that will support 3D segmentation. This will cause major changes in the API that might affect you. Check the draft PR for a succint description of what will happen:
https://github.com/trackmate-sc/TrackMate/pull/263

But in any case we will be there to help with porting your code to the future new v8, to be out probably early next year or for Christmas.

**Comment by jiyuuchc** [comment]
Did a quick scan of #263. It seems that the API changes are relatively minor. We would like to aim for a synchronized release. I assume the v8 branch is the one we should track for our own developmental branch?


________________________________________

**Comment by tinevez** [comment]
Yes absolutely. 
Anything else? Can I close this issue?

**Comment by jiyuuchc** [comment]
Certainly. Thanks for the reply.

Ji

________________________________________
